/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HttpSchemaKickstartdsComTokensColorSchemaJson {
  ks: {
    color: {
      primary: {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      "primary-inverted": {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      fg: {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      "fg-inverted": {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      link: {
        base?: {
          value:
            | string
            | {
                [k: string]: number;
              };
          attributes: {
            category: "color";
            [k: string]: unknown;
          };
          token?: {
            category: string;
            presenter: string;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      "link-inverted": {
        base?: {
          value:
            | string
            | {
                [k: string]: number;
              };
          attributes: {
            category: "color";
            [k: string]: unknown;
          };
          token?: {
            category: string;
            presenter: string;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      transparent: {
        base?: {
          value:
            | string
            | {
                [k: string]: number;
              };
          attributes: {
            category: "color";
            [k: string]: unknown;
          };
          token?: {
            category: string;
            presenter: string;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      positive?: {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      "positive-inverted"?: {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      informative?: {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      "informative-inverted"?: {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      notice?: {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      "notice-inverted"?: {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      negative?: {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      "negative-inverted"?: {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
      [k: string]: {
        base: {
          base?: {
            value:
              | string
              | {
                  [k: string]: number;
                };
            attributes: {
              category: "color";
              [k: string]: unknown;
            };
            token?: {
              category: string;
              presenter: string;
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        alpha: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
        "to-bg": {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[1-9]$".
           */
          [k: string]: {
            base?: {
              value:
                | string
                | {
                    [k: string]: number;
                  };
              attributes: {
                category: "color";
                [k: string]: unknown;
              };
              token?: {
                category: string;
                presenter: string;
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
        };
      };
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
